package middleware

// ObserverAccountRouteAllowed is an explicit capability allowlist. Keep system
// update, settings, users, groups and proxy mutations administrator-only. The
// account handler guard separately authorizes every account/group reference.
func ObserverAccountRouteAllowed(method, route string) bool {
	_, ok := observerAccountRoutes[method+" "+route]
	return ok
}

var observerAccountRoutes = map[string]struct{}{
	"GET /api/v1/admin/accounts/:id/scheduled-test-plans":            {},
	"POST /api/v1/admin/scheduled-test-plans":                        {},
	"PUT /api/v1/admin/scheduled-test-plans/:id":                     {},
	"DELETE /api/v1/admin/scheduled-test-plans/:id":                  {},
	"GET /api/v1/admin/scheduled-test-plans/:id/results":             {},
	"GET /api/v1/admin/scheduled-test-plans/:id/results/:resultID":   {},
	"GET /api/v1/admin/accounts/management-capabilities":             {},
	"GET /api/v1/admin/accounts":                                     {},
	"GET /api/v1/admin/accounts/upstream-billing-rates":              {},
	"GET /api/v1/admin/accounts/upstream-billing-probe/settings":     {},
	"POST /api/v1/admin/accounts/upstream-billing-probe/batch":       {},
	"GET /api/v1/admin/accounts/ollama-cloud-usage/settings":         {},
	"PUT /api/v1/admin/accounts/:id/codex-skip-harvest":              {},
	"POST /api/v1/admin/accounts/:id/manual-harvest":                 {},
	"GET /api/v1/admin/accounts/opencode-go-usage/settings":          {},
	"GET /api/v1/admin/accounts/:id":                                 {},
	"POST /api/v1/admin/accounts":                                    {},
	"POST /api/v1/admin/accounts/:id/duplicate":                      {},
	"POST /api/v1/admin/accounts/check-mixed-channel":                {},
	"POST /api/v1/admin/accounts/import/codex-session":               {},
	"PUT /api/v1/admin/accounts/:id":                                 {},
	"GET /api/v1/admin/accounts/:id/grok-media-eligibility":          {},
	"PUT /api/v1/admin/accounts/:id/grok-media-eligibility":          {},
	"PUT /api/v1/admin/accounts/:id/upstream-billing-probe":          {},
	"POST /api/v1/admin/accounts/:id/upstream-billing-probe":         {},
	"GET /api/v1/admin/accounts/:id/ollama-cloud-usage":              {},
	"PUT /api/v1/admin/accounts/:id/ollama-cloud-usage/session":      {},
	"DELETE /api/v1/admin/accounts/:id/ollama-cloud-usage/session":   {},
	"PUT /api/v1/admin/accounts/:id/ollama-cloud-usage/auto-refresh": {},
	"POST /api/v1/admin/accounts/:id/ollama-cloud-usage/refresh":     {},
	"GET /api/v1/admin/accounts/:id/opencode-go-usage":               {},
	"PUT /api/v1/admin/accounts/:id/opencode-go-usage/auto-refresh":  {},
	"POST /api/v1/admin/accounts/:id/opencode-go-usage/refresh":      {},
	"DELETE /api/v1/admin/accounts/:id":                              {},
	"POST /api/v1/admin/accounts/:id/test":                           {},
	"POST /api/v1/admin/accounts/:id/pelican-test":                   {},
	"POST /api/v1/admin/accounts/:id/recover-state":                  {},
	"POST /api/v1/admin/accounts/:id/refresh":                        {},
	"POST /api/v1/admin/accounts/:id/apply-oauth-credentials":        {},
	"POST /api/v1/admin/accounts/:id/set-privacy":                    {},
	"POST /api/v1/admin/accounts/:id/refresh-tier":                   {},
	"GET /api/v1/admin/accounts/:id/stats":                           {},
	"POST /api/v1/admin/accounts/:id/clear-error":                    {},
	"POST /api/v1/admin/accounts/:id/revert-proxy-fallback":          {},
	"GET /api/v1/admin/accounts/:id/usage":                           {},
	"GET /api/v1/admin/accounts/:id/today-stats":                     {},
	"POST /api/v1/admin/accounts/usage/batch":                        {},
	"POST /api/v1/admin/accounts/today-stats/batch":                  {},
	"POST /api/v1/admin/accounts/:id/clear-rate-limit":               {},
	"POST /api/v1/admin/accounts/:id/reset-quota":                    {},
	"GET /api/v1/admin/accounts/:id/temp-unschedulable":              {},
	"DELETE /api/v1/admin/accounts/:id/temp-unschedulable":           {},
	"POST /api/v1/admin/accounts/:id/schedulable":                    {},
	"POST /api/v1/admin/accounts/models/sync-upstream-preview":       {},
	"GET /api/v1/admin/accounts/:id/models":                          {},
	"POST /api/v1/admin/accounts/:id/models/sync-upstream":           {},
	"POST /api/v1/admin/accounts/batch":                              {},
	"GET /api/v1/admin/accounts/data":                                {},
	"POST /api/v1/admin/accounts/data":                               {},
	"POST /api/v1/admin/accounts/batch-update-credentials":           {},
	"POST /api/v1/admin/accounts/batch-refresh-tier":                 {},
	"POST /api/v1/admin/accounts/bulk-update":                        {},
	"POST /api/v1/admin/accounts/batch-delete":                       {},
	"POST /api/v1/admin/accounts/batch-clear-error":                  {},
	"POST /api/v1/admin/accounts/batch-refresh":                      {},
	"GET /api/v1/admin/accounts/antigravity/default-model-mapping":   {},
	"POST /api/v1/admin/accounts/:id/shadow":                         {},
	"POST /api/v1/admin/accounts/generate-auth-url":                  {},
	"POST /api/v1/admin/accounts/generate-setup-token-url":           {},
	"POST /api/v1/admin/accounts/exchange-code":                      {},
	"POST /api/v1/admin/accounts/exchange-setup-token-code":          {},
	"POST /api/v1/admin/accounts/cookie-auth":                        {},
	"POST /api/v1/admin/accounts/setup-token-cookie-auth":            {},
	"POST /api/v1/admin/openai/generate-auth-url":                    {},
	"POST /api/v1/admin/openai/exchange-code":                        {},
	"POST /api/v1/admin/openai/refresh-token":                        {},
	"POST /api/v1/admin/openai/accounts/:id/refresh":                 {},
	"POST /api/v1/admin/openai/create-from-oauth":                    {},
	"POST /api/v1/admin/openai/create-from-codex-pat":                {},
	"GET /api/v1/admin/openai/accounts/:id/quota":                    {},
	"POST /api/v1/admin/openai/accounts/:id/quota/refresh":           {},
	"POST /api/v1/admin/openai/accounts/:id/reset-quota":             {},
	"POST /api/v1/admin/openai/accounts/:id/referrals/refresh":       {},
	"POST /api/v1/admin/openai/accounts/:id/referrals/invite":        {},
	"POST /api/v1/admin/gemini/oauth/auth-url":                       {},
	"POST /api/v1/admin/gemini/oauth/exchange-code":                  {},
	"GET /api/v1/admin/gemini/oauth/capabilities":                    {},
	"POST /api/v1/admin/antigravity/oauth/auth-url":                  {},
	"POST /api/v1/admin/antigravity/oauth/exchange-code":             {},
	"POST /api/v1/admin/antigravity/oauth/refresh-token":             {},
	"GET /api/v1/admin/grok/oauth/capabilities":                      {},
	"POST /api/v1/admin/grok/oauth/auth-url":                         {},
	"POST /api/v1/admin/grok/oauth/exchange-code":                    {},
	"POST /api/v1/admin/grok/oauth/refresh-token":                    {},
	"POST /api/v1/admin/grok/oauth/sso-token":                        {},
	"POST /api/v1/admin/grok/oauth/password":                         {},
	"POST /api/v1/admin/grok/oauth/create-from-oauth":                {},
	"POST /api/v1/admin/grok/sso-to-oauth":                           {},
	"POST /api/v1/admin/grok/accounts/:id/refresh":                   {},
	"GET /api/v1/admin/grok/accounts/:id/quota":                      {},
	"POST /api/v1/admin/grok/accounts/:id/reset-quota":               {},
	"GET /api/v1/admin/cn-providers/accounts/:id/quota":              {},
	"GET /api/v1/admin/cn-providers/accounts/:id/balance":            {},
	"GET /api/v1/admin/groups/all":                                   {},
	"GET /api/v1/admin/proxies/all":                                  {},
	"GET /api/v1/admin/tls-fingerprint-profiles":                     {},
}
