import type { GroupPlatform } from '@/types'

export const CODEX_QUICK_CONFIG_PLATFORMS = [
  'openai',
  'anthropic',
  'gemini',
  'antigravity',
  'grok',
  'kimi',
  'zhipu',
  'deepseek',
  'minimax',
  'opencode_go',
  'composite'
] as const satisfies readonly GroupPlatform[]

export type CodexQuickConfigPlatform = typeof CODEX_QUICK_CONFIG_PLATFORMS[number]

const codexQuickConfigPlatforms = new Set<GroupPlatform>(CODEX_QUICK_CONFIG_PLATFORMS)

export function isCodexQuickConfigPlatform(
  platform: GroupPlatform | null | undefined
): platform is CodexQuickConfigPlatform {
  return platform != null && codexQuickConfigPlatforms.has(platform)
}

export interface CodexQuickConfigInput {
  apiKey: string
  baseUrl: string
  platform?: CodexQuickConfigPlatform | null
  modelCatalogContent?: string
  modelCatalogPath?: string
}

const preferredModels: Record<CodexQuickConfigPlatform, string> = {
  openai: 'gpt-5.5',
  anthropic: 'claude-sonnet-4-6',
  gemini: 'gemini-2.5-pro',
  antigravity: 'claude-sonnet-4-6',
  grok: 'grok-4.5',
  kimi: 'kimi-k2.5',
  zhipu: 'glm-4.7',
  deepseek: 'deepseek-v4-pro',
  minimax: 'MiniMax-M3',
  opencode_go: 'glm-5.3',
  composite: 'gpt-5.5'
}

const providerNames: Record<CodexQuickConfigPlatform, string> = {
  openai: 'OpenAI',
  anthropic: 'Sub2API Anthropic',
  gemini: 'Sub2API Gemini',
  antigravity: 'Sub2API Antigravity',
  grok: 'Sub2API Grok',
  kimi: 'Sub2API Kimi',
  zhipu: 'Sub2API Zhipu',
  deepseek: 'Sub2API DeepSeek',
  minimax: 'Sub2API MiniMax',
  opencode_go: 'Sub2API OpenCode',
  composite: 'Sub2API Composite'
}

function escapeTomlBasicString(value: string): string {
  return value
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    // TOML basic strings forbid unescaped control characters.
    // eslint-disable-next-line no-control-regex
    .replace(/[\x00-\x1f\x7f]/g, (character) => `\\u${character.charCodeAt(0).toString(16).padStart(4, '0')}`)
}

export function normalizeCodexBaseUrl(baseUrl: string): string {
  const trimmed = baseUrl.trim().replace(/\/+$/, '')
  if (!trimmed) return ''
  return /\/v1$/i.test(trimmed) ? trimmed : `${trimmed}/v1`
}

export function encodeUtf8Base64(value: string): string {
  const bytes = new TextEncoder().encode(value)
  let binary = ''
  for (const byte of bytes) binary += String.fromCharCode(byte)
  return btoa(binary)
}

function encodeUtf16LeBase64(value: string): string {
  let binary = ''
  for (let index = 0; index < value.length; index += 1) {
    const codeUnit = value.charCodeAt(index)
    binary += String.fromCharCode(codeUnit & 0xff, codeUnit >> 8)
  }
  return btoa(binary)
}

export function buildCodexQuickConfigToml(input: CodexQuickConfigInput): string {
  const platform = input.platform || 'openai'
  const model = preferredModels[platform] || preferredModels.openai
  const provider = platform === 'openai' ? 'OpenAI' : 'sub2api'
  const providerName = providerNames[platform] || 'Sub2API'
  const catalogLine = input.modelCatalogContent
    ? `model_catalog_json = "${escapeTomlBasicString(input.modelCatalogPath || '~/.codex/codex-models.json')}"\n`
    : ''

  return `# Generated by Sub2API. Re-running the setup script replaces this file.
model_provider = "${provider}"
model = "${escapeTomlBasicString(model)}"
review_model = "${escapeTomlBasicString(model)}"
disable_response_storage = true
network_access = "enabled"
windows_wsl_setup_acknowledged = true
${catalogLine}
[model_providers.${provider}]
name = "${escapeTomlBasicString(providerName)}"
base_url = "${escapeTomlBasicString(normalizeCodexBaseUrl(input.baseUrl))}"
wire_api = "responses"
requires_openai_auth = false
experimental_bearer_token = "${escapeTomlBasicString(input.apiKey)}"
http_headers = { "x-openai-actor-authorization" = "local-image-extension" }
supports_websockets = false

[features]
goals = true
`
}

export function buildMacLinuxCodexQuickConfigScript(input: CodexQuickConfigInput): string {
  // The catalog path must be resolved on the target machine, not in the browser.
  const configPayload = encodeUtf8Base64(buildCodexQuickConfigToml({ ...input, modelCatalogContent: undefined }))
  const catalogPayload = input.modelCatalogContent ? encodeUtf8Base64(input.modelCatalogContent) : ''
  const catalogBlock = catalogPayload
    ? `if [ -d "${'${CONFIG_DIR}'}/codex-models.json" ]; then
  printf '模型目录文件路径已被文件夹占用。\\n' >&2
  exit 1
fi
CATALOG_PAYLOAD='${catalogPayload}'
CATALOG_TMP_FILE="$(mktemp "${'${CONFIG_FILE}'}.catalog.tmp.XXXXXX")"
decode_payload "${'${CATALOG_PAYLOAD}'}" > "${'${CATALOG_TMP_FILE}'}"
mv -f "${'${CATALOG_TMP_FILE}'}" "${'${CONFIG_DIR}'}/codex-models.json"
`
    : ''
  const catalogPathBlock = catalogPayload
    ? `CATALOG_PATH="${'${CONFIG_DIR}'}/codex-models.json"
CATALOG_PATH="${'${CATALOG_PATH//\\\\/\\\\\\\\}'}"
CATALOG_PATH="${'${CATALOG_PATH//\\\"/\\\\\\\"}'}"
CATALOG_PATH="${'${CATALOG_PATH//$\'\\n\'/\\\\n}'}"
CATALOG_PATH="${'${CATALOG_PATH//$\'\\r\'/\\\\r}'}"
CATALOG_PATH="${'${CATALOG_PATH//$\'\\t\'/\\\\t}'}"
printf 'model_catalog_json = "%s"\\n' "${'${CATALOG_PATH}'}" > "${'${TMP_FILE}'}"
`
    : ''

  return `#!/usr/bin/env bash
set -euo pipefail
# Keep feedback visible even when Bash 3 runs EXIT inside a redirected function.
exec 3>&1
umask 077
export PATH="${'${PATH:-}'}:/usr/bin:/bin"

CONFIG_DIR="${'${CODEX_HOME:-${HOME}/.codex}'}"
CONFIG_FILE="${'${CONFIG_DIR}'}/config.toml"
TMP_FILE=''
CATALOG_TMP_FILE=''

finish() {
  status=$?
  trap - EXIT
  [ -z "$TMP_FILE" ] || rm -f "$TMP_FILE" || :
  [ -z "$CATALOG_TMP_FILE" ] || rm -f "$CATALOG_TMP_FILE" || :
  if [ "$status" -eq 0 ]; then
    message="Codex 配置成功。
配置文件：$CONFIG_FILE
请完全退出并重启 Codex 以加载新配置。"
    dialog_kind='success'
  else
    message="Codex 配置失败。
配置文件：$CONFIG_FILE
请检查终端错误信息、目录权限和磁盘空间后重试。"
    dialog_kind='error'
  fi
  printf '%s\\n' "$message" >&3
  if [ "$(uname -s)" = 'Darwin' ] && command -v osascript >/dev/null 2>&1; then
    osascript - "$message" "$dialog_kind" >/dev/null 2>&1 <<'APPLESCRIPT' || :
on run argv
  if item 2 of argv is "success" then
    display dialog (item 1 of argv) with title "Sub2API - Codex" buttons {"好"} default button 1 with icon note
  else
    display dialog (item 1 of argv) with title "Sub2API - Codex" buttons {"好"} default button 1 with icon stop
  end if
end run
APPLESCRIPT
  fi
  exit "$status"
}
trap finish EXIT

if printf '' | base64 --decode >/dev/null 2>&1; then
  BASE64_DECODE_FLAG='--decode'
elif printf '' | base64 -D >/dev/null 2>&1; then
  BASE64_DECODE_FLAG='-D'
else
  printf '系统 base64 组件不可用。\\n' >&2
  exit 1
fi
decode_payload() {
  printf '%s' "$1" | base64 "$BASE64_DECODE_FLAG"
}

mkdir -p "${'${CONFIG_DIR}'}"
CONFIG_DIR="$(cd "${'${CONFIG_DIR}'}" && pwd -P)"
CONFIG_FILE="${'${CONFIG_DIR}'}/config.toml"
if [ -d "${'${CONFIG_FILE}'}" ]; then
  printf '配置文件路径已被文件夹占用。\\n' >&2
  exit 1
fi
TMP_FILE="$(mktemp "${'${CONFIG_FILE}'}.tmp.XXXXXX")"

PAYLOAD='${configPayload}'
${catalogPathBlock}decode_payload "${'${PAYLOAD}'}" >> "${'${TMP_FILE}'}"

${catalogBlock}mv -f "${'${TMP_FILE}'}" "${'${CONFIG_FILE}'}"
`
}

export function buildWindowsCmdCodexQuickConfigScript(input: CodexQuickConfigInput): string {
  const configPayload = encodeUtf8Base64(buildCodexQuickConfigToml({ ...input, modelCatalogContent: undefined }))
  const catalogPayload = input.modelCatalogContent ? encodeUtf8Base64(input.modelCatalogContent) : ''
  const psPayload = (payload: string) => (payload.match(/.{1,2000}/g) || [])
    .map((chunk) => `  '${chunk}'`).join(',\n')
  const catalogBlock = catalogPayload
    ? `  $catalogPayload = @(
${psPayload(catalogPayload)}
  ) -join ''
  $catalogFile = [IO.Path]::Combine($configDir, 'codex-models.json')
  $catalogBackup = $catalogFile + '.backup.' + [Guid]::NewGuid().ToString('N')
  $catalogTemp = $catalogFile + '.tmp.' + [Guid]::NewGuid().ToString('N')
  $tempFiles += $catalogTemp
  [IO.File]::WriteAllBytes($catalogTemp, [Convert]::FromBase64String($catalogPayload))
  $catalogPath = $catalogFile.Replace('\\', '\\\\').Replace('"', '\\"')
  $config = 'model_catalog_json = "' + $catalogPath + '"' + [Environment]::NewLine + $config
`
    : ''
  const bootstrapPayload = encodeUtf16LeBase64(
    `$ErrorActionPreference = 'Stop'; try { $source = [IO.File]::ReadAllText($env:SUB2API_CODEX_SCRIPT); $marker = '# SUB2API_POWERSHELL'; & ([ScriptBlock]::Create($source.Substring($source.LastIndexOf($marker) + $marker.Length))) } catch { [Console]::Error.WriteLine($_.Exception.Message); exit 1 }`
  )

  // Only the short bootstrap is interpreted by CMD. Payloads stay out of its
  // 8191-character command/environment limit, and the entire file is ASCII.
  return `@echo off
setlocal EnableExtensions DisableDelayedExpansion
set "SUB2API_CODEX_SCRIPT=%~f0"
set "SUB2API_POWERSHELL=%SystemRoot%\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"
if exist "%SystemRoot%\\Sysnative\\WindowsPowerShell\\v1.0\\powershell.exe" set "SUB2API_POWERSHELL=%SystemRoot%\\Sysnative\\WindowsPowerShell\\v1.0\\powershell.exe"
if not exist "%SUB2API_POWERSHELL%" goto :missing_powershell
set "SUB2API_CODEX_EXIT=1"
"%SUB2API_POWERSHELL%" -NoLogo -NoProfile -NonInteractive -STA -ExecutionPolicy Bypass -EncodedCommand ${bootstrapPayload}
if not errorlevel 1 if errorlevel 0 set "SUB2API_CODEX_EXIT=0"
pause
endlocal & exit /b %SUB2API_CODEX_EXIT%

:missing_powershell
echo Codex configuration failed: Windows PowerShell is unavailable. 1>&2
echo Enable the built-in Windows PowerShell component and run this file again. 1>&2
pause
endlocal
exit /b 1

# SUB2API_POWERSHELL
$ErrorActionPreference = 'Stop'
$tempFiles = @()
$status = 1
$configFile = ''
$catalogPublished = $false
$catalogBackup = ''
try { [Console]::OutputEncoding = [Text.Encoding]::UTF8 } catch { }
function Decode-Text([string]$value) {
  return [Text.Encoding]::UTF8.GetString([Convert]::FromBase64String($value))
}
function Publish-File([string]$source, [string]$destination, [string]$backup = '') {
  if ([IO.File]::Exists($destination)) {
    if ($backup) {
      [IO.File]::Replace($source, $destination, $backup)
    } else {
      # PowerShell converts $null to an empty string for .NET string parameters.
      [IO.File]::Replace($source, $destination, [System.Management.Automation.Language.NullString]::Value)
    }
  } else {
    [IO.File]::Move($source, $destination)
  }
}
try {
  $configDir = $env:CODEX_HOME
  if ([string]::IsNullOrWhiteSpace($configDir)) {
    $configDir = [IO.Path]::Combine([Environment]::GetFolderPath('UserProfile'), '.codex')
  }
  $configDir = [IO.Path]::GetFullPath($configDir)
  $configFile = [IO.Path]::Combine($configDir, 'config.toml')
  [void][IO.Directory]::CreateDirectory($configDir)
  $configPayload = @(
${psPayload(configPayload)}
  ) -join ''
  $config = Decode-Text $configPayload
${catalogBlock}  $configTemp = $configFile + '.tmp.' + [Guid]::NewGuid().ToString('N')
  $tempFiles += $configTemp
  [IO.File]::WriteAllBytes($configTemp, [Text.Encoding]::UTF8.GetBytes($config))
${catalogPayload ? '  Publish-File $catalogTemp $catalogFile $catalogBackup\n  $catalogPublished = $true\n' : ''}  Publish-File $configTemp $configFile
  $status = 0
  $message = (Decode-Text '${encodeUtf8Base64('Codex 配置成功。')}') + [Environment]::NewLine + $configFile + [Environment]::NewLine + (Decode-Text '${encodeUtf8Base64('请完全退出并重启 Codex 以加载新配置。')}')
} catch {
  $failure = $_.Exception.Message
  if ($catalogPublished) {
    try {
      if ([IO.File]::Exists($catalogBackup)) {
        Publish-File $catalogBackup $catalogFile
      } else {
        [IO.File]::Delete($catalogFile)
      }
    } catch {
      $failure += [Environment]::NewLine + 'Could not restore the model catalog. Backup: ' + $catalogBackup + [Environment]::NewLine + $_.Exception.Message
    }
  }
  $message = (Decode-Text '${encodeUtf8Base64('Codex 配置失败。请检查目录权限、磁盘空间和终端错误信息后重试。')}') + [Environment]::NewLine + $configFile + [Environment]::NewLine + $failure
} finally {
  # Keep the original catalog backup if rollback failed.
  if ($status -eq 0 -and $catalogBackup) { $tempFiles += $catalogBackup }
  foreach ($file in $tempFiles) {
    try { if ([IO.File]::Exists($file)) { [IO.File]::Delete($file) } } catch { }
  }
}
[Console]::WriteLine($message)
try {
  $shell = New-Object -ComObject WScript.Shell
  $icon = 16
  if ($status -eq 0) { $icon = 64 }
  [void]$shell.Popup($message, 0, 'Sub2API - Codex', $icon)
} catch {
  [Console]::WriteLine('System dialog unavailable. See the result above.')
}
exit $status
`
    .replace(/\n/g, '\r\n')
}
